security:
  basic:
    enabled: true

server:
  port: 8443
    # The format used for the keystore. It could be set to JKS in case it is a JKS file
  ssl:
    key-store-type: PKCS12
    key-store: "classpath:ssl/maprdeployer.p12"
    key-store-password: mapr123
    key-alias: maprdeployer

maprdeployui:
#  terraform_project_path: C:/Projects/workspaces/terraform-mapr/
#  terraform_project_path: /mnt/c/Projects/workspaces/terraform-mapr/
#  terraform_binary_path: C:/Projects/workspaces/mapr-terraform-ui/mock/terraform_deploy.bat
#  terraform_binary_path:  C:/Projects/workspaces/mapr-terraform-ui/mock/terraform_destroy.bat

# Prod
# TODO should be configurable
  terraform_project_path: /opt/maprterraform/
  terraform_binary_path: /usr/local/bin/terraform

  deploy_ssh_public_key_path: /home/mapr/.ssh/id_rsa.pub
  deploy_ssh_private_key_path: /home/mapr/.ssh/id_rsa
  login_username: admin
  login_password: MpHfLE7cpdRS


wicket:
  core:
    resourcesettings:
      packageresourceguard:
        pattern:
          - +*.map
#server:
#  compression:
#    enabled: true
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: none