security:
  basic:
    enabled: false

maprdeployui:
  terraform_project_path: C:/Projects/workspaces/terraform-mapr/
  terraform_binary_path: /usr/bin/terraform


wicket:
  core:
    resourcesettings:
      packageresourceguard:
        pattern:
          - +*.map
#server:
#  compression:
#    enabled: true
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: none