security:
  basic:
    enabled: false

server:
  port : 8080

maprdeployui:
#  terraform_project_path: C:/Projects/workspaces/terraform-mapr/
#  terraform_project_path: /mnt/c/Projects/workspaces/terraform-mapr/
  terraform_binary_path: C:/Projects/workspaces/mapr-terraform-ui/mock/terraform_deploy.bat
#  terraform_binary_path:  C:/Projects/workspaces/mapr-terraform-ui/mock/terraform_destroy.bat

# Prod
  terraform_project_path: /opt/maprterraform/
#  terraform_binary_path: /usr/bin/terraform
  deploy_ssh_public_key_path: /home/ec2-user/.ssh/id_rsa.pub
  deploy_ssh_private_key_path: /home/ec2-user/.ssh/id_rsa

wicket:
  core:
    resourcesettings:
      packageresourceguard:
        pattern:
          - +*.map
#server:
#  compression:
#    enabled: true
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: none